<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>JS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.js</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.js</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;==|\()\s*/</string>
			<key>end</key>
			<string>/[gim]*</string>
			<key>name</key>
			<string>string.regexp.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\{|,)\s*[A-Za-z$_]+\s*(?=(:|=)\s*function)|^\s*[A-Za-z$_]+\s*(?=(:|=)\s*function)</string>
			<key>name</key>
			<string>support.function.js</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>highlight delete, typeof, void, instanceof as operator</string>
			<key>match</key>
			<string>\b(break|function|return|case|do|if|switch|var|catch|else|in|this|continue|false|throw|while|debugger|finally|new|true|with|default|for|null|try|class|const|enum|export|extends|import|super|implements|let|private|public|yield|interface|package|protected|static|arguments|eval)\b</string>
			<key>name</key>
			<string>keyword.reserved.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b|\bNaN\b|-?\bInfinity\b|\b0(x|X)[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|/|%|=|!|\^|~|\||&lt;|&gt;|&amp;|\bdelete\b|\btypeof\b|\bvoid\b|\binstanceof\b|\bin\b</string>
			<key>name</key>
			<string>keyword.operator.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b[A-Za-z0-9$_]+(?=\.|\s*=\s*\{)</string>
			<key>name</key>
			<string>object-name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b[A-Za-z0-9$_]+(?=\[|\s*=\s*\[)</string>
			<key>name</key>
			<string>array-name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)[A-Za-z$_]+(?=\.|\s|,|;|\[|\]|\)|\?|\+|\-|=)|(?&lt;=\{|,)\s*[A-Za-z$_]+\s*(?=:)|^\s*[A-Za-z$_]+\s*(?=:)</string>
			<key>name</key>
			<string>support.constant.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)[A-Za-z$_]+(?=\()|[A-Za-z$_]+(?=\()</string>
			<key>name</key>
			<string>support.function.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z0-9$_]+</string>
			<key>name</key>
			<string>variable.js</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\.{1}</string>
			<key>name</key>
			<string>constant.character.escape.js</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js</string>
	<key>uuid</key>
	<string>B0029020-D78F-11E3-9C1A-0800200C9A66</string>
</dict>
</plist>
