<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>json</string>
		<string>sublime-settings</string>
		<string>sublime-menu</string>
		<string>sublime-keymap</string>
		<string>sublime-mousemap</string>
		<string>sublime-theme</string>
		<string>sublime-build</string>
		<string>sublime-project</string>
		<string>sublime-completions</string>
	</array>
	<key>name</key>
	<string>JSON</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>variable.json</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>end</key>
			<string>(?=,|\{|\}|\[)</string>
			<key>name</key>
			<string>json-entry</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>".*"\s*:|:</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|null)\b</string>
					<key>name</key>
					<string>constant.language.json</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b|\bNaN\b|-?\bInfinity\b|\b0(x|X)[0-9a-fA-F]+</string>
					<key>name</key>
					<string>constant.numeric.js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-line</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.js</string>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.js</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\.{1}</string>
			<key>name</key>
			<string>constant.character.escape.js</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>[A-Za-z_']*</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.json</string>
	<key>uuid</key>
	<string>597038B0-E83E-11E3-AC10-0800200C9A66</string>
</dict>
</plist>